package ExceptionHandling.practice;

public class Exception4 {
	
	public static void main ()throws ArrayStoreException ,NullPointerException{
		
		int a []=new  int[6];
		a[0]=1;
		a[1]=2;
		a[2]=3;
		a[3]=4;
		a[4]=5;
		
		String s=null;
		
	
		
		
	}
	
	
	
	
	public static void main(String[] args) {
		
		Exception4 e =new Exception4();
		e.main();
		System.out.println("fine");
		
		
		
	}

}
